#!/applications/R/R-3.5.0/bin/Rscript

# Based on model comparisons generated by regression_SNP_count_per_win_COs.R,
# use ZINB regression models to compare populations SNP counts in the window
# that overlaps the midpoint of crossover intervals, and tabulate model summaries

# Usage from within directory containing windowed CO counts files:
# ./regression_SNP_count_per_win_COs_midpoints.R coller.filtarb coller.filtmsh2 15000 15kb

library(parallel)
library(MASS) # glm.nb() included
library(pscl) # zeroinfl() included
library(AER) # dispersiontest() included

#pop1Name <- "coller.filtarb"
#pop2Name <- "coller.filtmsh2"
#flankSize <- 15000
#flankName <- "15kb"

args <- commandArgs(trailingOnly = TRUE)
pop1Name <- args[1]
pop2Name <- args[2]
flankSize <- as.numeric(args[3])
flankName <- as.character(args[4])

midWin <- ((flankSize+winSize)/winSize)

matDir <- "matrices/"

# Define and create new directories and subdirectories
# to contain results
sizeDir <- paste0(flankName, "_flank_", winNames, "_win/")
outDir <- paste0(sizeDir, "regression_models/")

winNames <- c("100bp", "200bp", "500bp", "1000bp", "1500bp", "2500bp", "5000bp")

dfs <- lapply(seq_along(winNames), function(x) {
  read.table(paste0(outDir[x], pop1Name, "_v_", pop2Name, "_SNP_frequency_",
                    "at_crossover_midpoints_", winNames[x], "_win.txt"),
             header = T)
})

colnames(genotype_ZINB_midWin_df) <- c("Window size", "Estimate", "2.5% CI", "97.5% CI", "Std. error", "Z-value", "P-value")
rownames(genotype_ZINB_midWin_df) <- c("Intercept", pop2Name, "Zero inflation")
write.table(genotype_ZINB_midWin_df,
            file = paste0(outDir, pop1Name, "_v_", pop2Name, "_SNP_frequency_",
                          "at_crossover_midpoints_", winName, "_win.txt"),
            row.names = T, col.names = T, sep = "\t", quote = F)
