#!/applications/R/R-3.5.0/bin/Rscript

# Based on model comparisons generated by regression_SNP_count_per_win_COs.R,
# use ZINB regression models to compare populations SNP counts in the window
# that overlaps the midpoint of crossover intervals, and tabulate model summaries

# Usage from within directory containing windowed CO counts files:
# ./regression_SNP_count_per_win_COs_midpoints_5000bp_win.R colclc.filtarb colclc.filtmsh2 15000 15kb 5000 5000bp 0.1

library(parallel)
library(MASS) # glm.nb() included
library(pscl) # zeroinfl() included
library(AER) # dispersiontest() included

#pop1Name <- "colclc.filtarb"
#pop2Name <- "colclc.filtmsh2"
#flankSize <- 15000
#flankName <- "15kb"
#winSize <- 5000
#winName <- "5000bp"
#FDR <- 0.1
#FDRname <- paste0("FDR", as.character(FDR))

args <- commandArgs(trailingOnly = TRUE)
pop1Name <- args[1]
pop2Name <- args[2]
flankSize <- as.numeric(args[3])
flankName <- as.character(args[4])
winSize <- as.numeric(args[5])
winName <- as.character(args[6])
FDR <- as.numeric(args[7])
FDRname <- paste0("FDR", as.character(FDR))

midWin <- ((flankSize+winSize)/winSize)

matDir <- "matrices/"

# Load matrices in which each row corresponds to a crossover or random locus
# and each column corresponds to a window within that locus
pop1_matList <- list(read.table(paste0(matDir,
                                       pop1Name, "_COs_SNP_frequency_feature_target_and_",
                                       flankName, "_flank_", winName, "_win_dataframe.txt"),
                                header = T),
                     read.table(paste0(matDir,
                                       pop1Name, "_COs_SNP_frequency_ranLoc_target_and_",
                                       flankName, "_flank_", winName, "_win_dataframe.txt"),
                                header = T))
pop2_matList <- list(read.table(paste0(matDir,
                                       pop2Name, "_COs_SNP_frequency_feature_target_and_",
                                       flankName, "_flank_", winName, "_win_dataframe.txt"),
                                header = T),
                     read.table(paste0(matDir,
                                       pop2Name, "_COs_SNP_frequency_ranLoc_target_and_",
                                       flankName, "_flank_", winName, "_win_dataframe.txt"),
                                header = T))

# Define and create new directories and subdirectories
# to contain results
sizeDir <- paste0(flankName, "_flank_", winName, "_win/")
outDir <- paste0(sizeDir, "regression_models/")
plotDir <- paste0(outDir, FDRname, "/")
system(paste0("[ -d ", sizeDir, " ] || mkdir ", sizeDir))
system(paste0("[ -d ", outDir, " ] || mkdir ", outDir))
system(paste0("[ -d ", plotDir, " ] || mkdir ", plotDir))

# Create a factor with two levels (pop1Name and pop2Name, corresponding to genotype)
# to be used as the predictor in regression models
genotype <- factor(c(rep(pop1Name, times = dim(pop1_matList[[1]])[1]),
                     rep(pop2Name, times = dim(pop2_matList[[1]])[1])),
                   levels = c(pop1Name, pop2Name))

# For each  window, fit regression models in which genotype is the
# predictor and SNP frequency is the response variable

## Poisson regression:
genotype_poisson <- lapply(seq_along(pop1_matList[[1]]), function(x) {
  glm(formula = c(pop1_matList[[1]][[x]], pop2_matList[[1]][[x]]) ~ genotype,
      family = poisson(link = "log"))
})

# Check if data are overdispersed
genotype_poisson_disp <- lapply(seq_along(genotype_poisson), function(x) {
  dispersiontest(genotype_poisson[[x]],
                 trafo = 1)
})
genotype_poisson_disp_Pvals <- sapply(seq_along(genotype_poisson_disp), function(x) {
  genotype_poisson_disp[[x]]$p.value
})


## Zero-inflated negative binomial regression:
# Note y ~ genotype | genotype , which is equivalent to y ~ genotype
# Required to obtain non-NaN Std. error, Z-value and P-value
# for 5000-bp middle window (midWin) model, where assumption that
# zero-inflation affects both genotypes equally does not hold
# (e.g., number of occurrences of 0 SNPs in middle windows of
# crossovers are significantly higher in the mutant population) 
# See https://stats.stackexchange.com/questions/209211/zero-inflated-poisson-regression-warning-message-in-sqrtdiagobjectvcov
genotype_ZINB <- mclapply(seq_along(pop1_matList[[1]]), function(x) {
  zeroinfl(formula = c(pop1_matList[[1]][[x]], pop2_matList[[1]][[x]]) ~ genotype | genotype,
           dist = "negbin")
}, mc.cores = detectCores())

# Tabulate results
genotype_ZINB_midWin_df <- data.frame("Window" = paste0(as.character(winSize), " bp"),
                                      "ZINB" = c("Intercept", pop2Name, "Zero inflation"),
                                      "Estimate" = as.vector(coef(genotype_ZINB[[midWin]])[1:3]),
                                      "2.5_CI" = as.vector(confint(genotype_ZINB[[midWin]])[,1][1:3]),
                                      "97.5_CI" = as.vector(confint(genotype_ZINB[[midWin]])[,2][1:3]),
                                      "Std_error" = c(as.vector(coef(summary(genotype_ZINB[[midWin]]))$count[,2][1:2]),
                                                      as.vector(coef(summary(genotype_ZINB[[midWin]]))$zero[,2][1])),
                                      "Z-value" = c(as.vector(coef(summary(genotype_ZINB[[midWin]]))$count[,3][1:2]),
                                                    as.vector(coef(summary(genotype_ZINB[[midWin]]))$zero[,3][1])),
                                      "P-value" = c(as.vector(coef(summary(genotype_ZINB[[midWin]]))$count[,4][1:2]),
                                                    as.vector(coef(summary(genotype_ZINB[[midWin]]))$zero[,4][1])))
colnames(genotype_ZINB_midWin_df) <- c("Window size", "ZINB", "Estimate", "2.5% CI", "97.5% CI", "Std. error", "Z-value", "P-value")
write.table(genotype_ZINB_midWin_df,
            file = paste0(outDir, pop1Name, "_v_", pop2Name, "_SNP_frequency_",
                          "at_crossover_midpoints_ZINB_", winName, "_win.tsv"),
            row.names = F, col.names = T, sep = "\t", quote = T)
